### ISSUE TITLE
PROJECT: TrackMaven 3.0 Redesign

### ISSUE THREAD

**Issue by grafxnerd** [grafxnerd/tmdesign#1]
- [x] Alerts page redesign #2 
- [ ] Resources front end dev #3
- [ ] About section front end dev #4
- [ ] Homepage design #5
- [ ] Start Tracking Flow design #6
